/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5grupo81.vistas;

import java.awt.Color;

/**
 *
 * @author joadz
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuFormulariodeAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuFormulariodeMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuManejodeInscripciones = new javax.swing.JMenuItem();
        jMenuManipulaciióndeNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuAlumnoporMateria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumnos");
        jMenu1.setPreferredSize(new java.awt.Dimension(80, 19));
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuFormulariodeAlumno.setText("Formulario de Alumno");
        jMenuFormulariodeAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFormulariodeAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuFormulariodeAlumno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materias");
        jMenu2.setPreferredSize(new java.awt.Dimension(90, 19));

        jMenuFormulariodeMateria.setText("Formulario de Materia");
        jMenuFormulariodeMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFormulariodeMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuFormulariodeMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administración");
        jMenu3.setPreferredSize(new java.awt.Dimension(130, 19));

        jMenuManejodeInscripciones.setText("Manejo de Inscripciones");
        jMenuManejodeInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManejodeInscripcionesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuManejodeInscripciones);

        jMenuManipulaciióndeNotas.setText("Manipulaciión de Notas");
        jMenu3.add(jMenuManipulaciióndeNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");
        jMenu4.setPreferredSize(new java.awt.Dimension(100, 19));

        jMenuAlumnoporMateria.setText("Alumno por Materia");
        jMenu4.add(jMenuAlumnoporMateria);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenu5.setPreferredSize(new java.awt.Dimension(60, 19));

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFormulariodeAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFormulariodeAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AlumnosVista alumno = new AlumnosVista();
        alumno.setVisible(true);
        alumno.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.add(alumno);

    }//GEN-LAST:event_jMenuFormulariodeAlumnoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuManejodeInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManejodeInscripcionesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        inscripcionVistas iV = new inscripcionVistas();
        iV.setVisible(true);
        escritorio.add(iV);
    }//GEN-LAST:event_jMenuManejodeInscripcionesActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        salirVistas sV = new salirVistas();
        sV.setVisible(true);
        escritorio.add(sV);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuFormulariodeMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFormulariodeMateriaActionPerformed
       escritorio.removeAll();
        escritorio.repaint();
        MateriasVista  materia= new MateriasVista();
        materia.setVisible(true);
        escritorio.add(materia);
    }//GEN-LAST:event_jMenuFormulariodeMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAlumnoporMateria;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFormulariodeAlumno;
    private javax.swing.JMenuItem jMenuFormulariodeMateria;
    private javax.swing.JMenuItem jMenuManejodeInscripciones;
    private javax.swing.JMenuItem jMenuManipulaciióndeNotas;
    private javax.swing.JMenuItem jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
