/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5grupo81.vistas;

/**
 *
 * @author joadz
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Alumnos = new javax.swing.JMenu();
        formAlumno = new javax.swing.JMenu();
        Materia = new javax.swing.JMenu();
        FormMateria = new javax.swing.JMenu();
        Administracion = new javax.swing.JMenu();
        manejoDeInscripciones = new javax.swing.JMenu();
        ManiDeNotas = new javax.swing.JMenu();
        Consulta = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Alumnos.setText("Alumno");
        Alumnos.setToolTipText("");

        formAlumno.setText("Formulario Alumno");
        Alumnos.add(formAlumno);

        jMenuBar1.add(Alumnos);

        Materia.setText("Materia");

        FormMateria.setText("Formulario Materia");
        Materia.add(FormMateria);

        jMenuBar1.add(Materia);

        Administracion.setText("Administración");

        manejoDeInscripciones.setText("Manejo de inscripciones");
        Administracion.add(manejoDeInscripciones);

        ManiDeNotas.setText("Manipulacion de notas");
        Administracion.add(ManiDeNotas);

        jMenuBar1.add(Administracion);

        Consulta.setText("Consulta");

        jMenu1.setText("jMenu1");
        Consulta.add(jMenu1);

        jMenuBar1.add(Consulta);

        Salir.setText("Salir");
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administracion;
    private javax.swing.JMenu Alumnos;
    private javax.swing.JMenu Consulta;
    private javax.swing.JMenu FormMateria;
    private javax.swing.JMenu ManiDeNotas;
    private javax.swing.JMenu Materia;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenu formAlumno;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu manejoDeInscripciones;
    // End of variables declaration//GEN-END:variables
}
